version: '3'
services:
  backend:
    container_name: mrs-backend
    build:
      context: ./backend/
    ports:
     - "5000:5000"
    volumes: 
     - ./backend/:/src
    environment:
    - CORPUS=korean_corpus.csv
    - APIPORT=5000
    - WEBWORKERS=1
  frontend:
    container_name: mrs-frontend
    build:
      context: ./frontend/
    command: bash -c "serve -s -l 3000 build"
    ports:
      - "3000:3000"
    volumes:
     - ./frontend/:/src
     - node_modules:/src/node_modules

volumes:
  node_modules: